= Getting started with Acorus
:Project: Acorus
:experimental:
:page-pagination:
:url-enwiki: https://en.wikipedia.org/wiki
:url-tutorial: https://github.com/stephengold/Acorus/blob/master/AcorusExamples/src/main/java/jme3utilities/ui/test

Ready for some actual code?


== HelloAcorus

{url-tutorial}/HelloAcorus.java[HelloAcorus] is a complete application
that provides a starting point for studying and using Acorus.
It's a simple extension of `AcorusDemo`:
one without a `FlyByCamera`, a `DebugKeysAppState`, or a `StatsAppState`.

A help node is displayed in the upper right corner of the viewport.
The help node describes the available user actions.
Two actions are available:

* "ScreenShot" (bound to either kbd:[Sys Rq] or kbd:[Scroll Lock]) and
* "SIMPLEAPP_Exit" (bound to kbd:[Esc]).

Code to handle the "ScreenShot" action is built into `ActionApplication`.
Pressing the bound key causes the application to capture a screenshot.

Pressing kbd:[Esc] triggers the "SIMPLEAPP_Exit" action.
Code to handle that action is also built into `ActionApplication`.
It causes the application to terminate.

Because action names are intended for display in help nodes,
they should ideally be short and descriptive.
"SIMPLEAPP_Exit" is part of the JMonkeyEngine legacy,
so the `buildNode()` utility method (which constructs the help node)
gives it special treatment.
That's why "exit" is displayed in place of the actual action name.

[IMPORTANT]
====
`HelloAcorus` is the first in a series of
example apps intended for hands-on learning.
I expect you to not only study the source code,
but to actually run the app as well.
Take time *now* to set up a
{url-enwiki}/Integrated_development_environment[software development environment]
for this purpose!

For instance, if you install Git and a Java Development Kit,
you should be able to launch example apps from a command shell, like so:

. `git clone https://github.com/stephengold/Acorus.git`
. `cd Acorus`
. `./gradlew HelloAcorus`
====

Here's that link to
{url-tutorial}/HelloAcorus.java[the HelloAcorus source code] again.


== Summary

* `HelloAcorus` is the starting point for both studying and using Acorus.
* A help node lists the available actions and describes how to trigger them.
* Action names should be short and descriptive.
* This is a hands-on tutoral. Please run the apps!
